create database sql_joins;
show databases;
use sql_joins;

# Create 2 tabkles (cricket/ foottballl)
create table cricket(cricket_id int auto_increment, name varchar(30), primary key(cricket_id));
create table foodball(football_id int auto_increment, name varchar(30), primary key(football_id));

rename table foodball TO football;
#truncate table cricket;
#truncate table football;
insert into cricket (name)
values('Stuart'),('Michael'),('Johnson'),('Hayden'),('Flaming');

insert into football (name)
values('Stuart'),('Johnson'),('Hayden'),('Langer'),('Astle');

select * from cricket;
select * from football;


# Inner join
# find the students that are part both cricket and fottball team
select * from cricket c 
inner join football f 
on c.name = f.name; 

select c.cricket_id, c.name, f.football_id, f.name
from cricket as c 
inner join football as f 
on c.name=f.name;

show databases;
use classicmodels;
show tables;

select * from products;

# Find the productCode, productName, textDescription for each of the products
select pro.productCode, pro.productName, pl.textDescription
from products pro 
inner join productlines pl
using (productline);
#on pro.productLine = pl.productLine;

#Find the revenue generated by each product order and status of the product
select o.ordernumber, o.status,sum(od.quantityordered * od.priceeach) as revenue
from orders o 
inner join orderdetails od on o.ordernumber=od.ordernumber
inner join products p on p.productcode=od.productcode
group by o.ordernumber, o.status
order by o.ordernumber;


#find the customer name and their order id
select c.customername,o.ordernumber from customers c 
left join orders o
on c.customernumber=o.customernumber;

#find the customer name and their order id who didnot keep order
select c.customername,o.ordernumber from customers c 
left join orders o
on c.customernumber=o.customernumber
where ordernumber is null;

#Find the customer name, customer phone number, email address of the employee
select c.customername,c.phone,e.employeenumber,e.email
from customers c 
right join employees e
on e.reportsTo=c.salesrepemployeenumber;

#SELF JOIN 
select * from employees;
# find who will report to whom
select concat(m.lastname,", ",m.firstname) as manager,
concat(e.lastname,", ",e.firstname) as employee 
from employees e 
inner join employees m
on m.employeenumber = e.reportsto
order by manager;

#FULL OUTER JOIN
select c.customername,o.ordernumber from customers c left join
orders as o
on c.customernumber=o.customernumber
union
select c.customername,o.ordernumber from customers c right join
orders as o
on c.customernumber=o.customernumber;